### PR TITLE
Add RC2 as a bad cipher, implement dictionary for bad ciphers / algorithims

### PR DESCRIPTION
**Pull request by antmldr**
Just some minor changes to allow the arbitrary addition of more ciphers and algorithms which are considered bad.

Also fixed a bug where the string formatter ({0}) from the messages.resx was getting rendered in the extension

### CODE REVIEW

**Comment by h3xstream** [comment]
I will take a look at your PR shortly. I will solve manually the conflict.

**Comment by h3xstream** [comment]
The result of the merge was transform to those two commits: 
fab69372cfe0eaa2d8fd86164d9309d095795400
d4fb155ce298dc6a7e899780875c70f848f497b9

The main reason I had to manually merge the code is that resx just before or just after you submit this PR.
The message are now handle with a single YAML file. The structure of the configuration will be more organic and easier to merge.

**Comment by h3xstream** [comment]
Thanks for the contributions.
If any part are missing, let me know.

**Comment by antmldr** [comment]
Nps, looking good & good modifications 👍

**Pull request closed without merging**
